language: generic

os: osx
osx_image: xcode6.4

install:
  - mkdir tmp && cd tmp
  - sw_vers -productVersion 
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -n pyopencl pyopencl pocl
  - conda activate pyopencl
  - python -c "import pyopencl as cl;cl.create_some_context()"
